language: python
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq automake autoconf libtool make zlib1g-dev python
script:
 - git clone --depth=50 git://github.com/glensc/file.git
 - cd file
 - git log -1
 - libtoolize --copy --force --install
 - aclocal
 - autoheader
 - autoconf
 - automake -a -c -f --foreign
 - ./configure --prefix=/usr
 - make -j4
 - sudo make install
 - cd ..
 - which file
 - file --version
 - python update-db.py file file/magic/Magdir
 - python fast-regression-test.py
